const $=s=>document.querySelector(s);
const fileInput=$("#fileInput"),dropZone=$("#dropZone"),fileInfo=$("#fileInfo"),fileName=$("#fileName"),pageCount=$("#pageCount"),previewCount=$("#previewCount"),startBtn=$("#startBtn"),progressBar=$("#progressBar"),progressText=$("#progressText"),statusEl=$("#status");
let selectedFile=null,sourceText="",pageDefinitions=[],frame=null,doc=null,nodes=[],currentPage=0,zoom=1,thumbStart=0;
const PAGE_RE=/docManager\\.addPage\\(\\{.*?pageNum:\\s*(\\d+).*?origWidth:\\s*([\\d.]+).*?origHeight:\\s*([\\d.]+).*?contentUrl:\\s*"([^"]+)"/gs;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function setProgress(v,t){progressBar.style.width=Math.max(0,Math.min(100,v))+"%";progressText.textContent=Math.round(v)+"%";if(t)statusEl.textContent=t;}
function parsePages(t){let a=[],s=new Set(),m;PAGE_RE.lastIndex=0;while(m=PAGE_RE.exec(t)){let n=+m[1];if(s.has(n))continue;s.add(n);a.push({number:n,width:+m[2],height:+m[3],url:m[4]})}return a.sort((a,b)=>a.number-b.number)}
function makeFrame(){const f=document.createElement("iframe");f.className="document-frame";f.setAttribute("aria-hidden","true");f.style.cssText="position:fixed;left:-100000px;top:0;width:1600px;height:1200px;border:0;visibility:hidden";document.body.appendChild(f);return f}
function cleanDoc(d){const s=d.createElement("style");s.id="scraper-clean-style";s.textContent=`html,body{margin:0!important;padding:0!important;background:#fff!important;overflow:visible!important}header,nav,footer,[class*="cookie"],[id*="cookie"],[class*="consent"],[id*="consent"],[class*="toolbar"],[class*="sidebar"],[class*="topbar"],[class*="bottom-bar"],[class*="modal"],[class*="overlay"],[class*="popup"]{display:none!important}`;(d.head||d.documentElement).appendChild(s)}
async function loadViewer(){frame=makeFrame();frame.srcdoc=sourceText;await new Promise(resolve=>{let done=false,finish=()=>{if(!done){done=true;resolve()}};frame.addEventListener("load",finish,{once:true});setTimeout(finish,15000)});doc=frame.contentDocument;if(!doc)throw new Error("The browser could not access the HTML viewer.");cleanDoc(doc);await sleep(3500);nodes=Array.from(doc.querySelectorAll('[id^="outer_page_"]'));if(!nodes.length)throw new Error("No document pages were rendered by the HTML viewer.")}
function pageStyle(index){return `#outer_page_${index+1}{display:block!important;visibility:visible!important;position:relative!important;left:auto!important;top:auto!important;margin:0 auto!important;}`}
function hidePages(){nodes.forEach(n=>{n.style.setProperty("display","none","important")})}
function preparePage(index){hidePages();const n=nodes[index];n.style.setProperty("display","block","important");n.style.setProperty("position","relative","important");n.style.setProperty("left","auto","important");n.style.setProperty("top","auto","important");n.style.setProperty("margin","0 auto","important");n.scrollIntoView({block:"center"});}
async function waitForContent(n){let last=0,stable=0;for(let i=0;i<30;i++){let size=n.querySelectorAll("img,canvas,svg,[style*='background']").length+n.textContent.trim().length;if(size===last)stable++;else stable=0;last=size;if(stable>=3)return;await sleep(200)}}
async function loadFile(file){if(!file)return;let ext=file.name.toLowerCase();if(!ext.endsWith(".html")&&!ext.endsWith(".htm")){alert("Please choose an HTML file.");return}selectedFile=file;const r=new FileReader();r.onload=async()=>{sourceText=r.result;pageDefinitions=parsePages(sourceText);fileName.textContent=file.name;pageCount.textContent=`${pageDefinitions.length} document pages detected`;previewCount.textContent=`${pageDefinitions.length} pages`;fileInfo.classList.remove("hidden");startBtn.disabled=!pageDefinitions.length;if(!pageDefinitions.length){setProgress(0,"No compatible Scribd page definitions found.");return}try{setProgress(2,"Loading document preview…");await loadViewer();currentPage=0;await showMainPage(0);await buildThumbs();setProgress(12,`Ready — ${nodes.length} pages detected.`)}catch(e){console.error(e);setProgress(0,"Preview could not be rendered.");alert("Preview failed.\n\n"+e.message)}};r.readAsText(file)}
async function showMainPage(index){if(!nodes.length)return;currentPage=Math.max(0,Math.min(nodes.length-1,index));preparePage(currentPage);await waitForContent(nodes[currentPage]);const stage=$("#viewerStage"),old=stage.querySelector("iframe");if(old)old.remove();const f=frame;f.style.position="absolute";f.style.left="0";f.style.top="0";f.style.width="100%";f.style.height="100%";f.style.visibility="visible";f.style.background="#fff";stage.appendChild(f);zoom=zoom||1;updateViewerScale();$("#viewerTitle").textContent=`Page ${currentPage+1} of ${nodes.length}`;updateNav();updateThumbs();}
function updateViewerScale(){if(!frame||!nodes[currentPage])return;const d=pageDefinitions[currentPage]||{width:902,height:507};const stage=$("#viewerStage");const maxW=stage.clientWidth-110,maxH=stage.clientHeight-40;let scale=Math.min(maxW/d.width,maxH/d.height);if(!Number.isFinite(scale)||scale<=0)scale=1;scale*=zoom;frame.contentDocument.body.style.display="flex";frame.contentDocument.body.style.alignItems="center";frame.contentDocument.body.style.justifyContent="center";frame.contentDocument.body.style.minHeight="100vh";frame.contentDocument.documentElement.style.overflow="hidden";const n=nodes[currentPage];n.style.transform=`scale(${scale})`;n.style.transformOrigin="center center";n.style.margin="0";$("#zoomText").textContent=zoom===1?"Fit":Math.round(zoom*100)+"%"}
function updateNav(){$("#prevPage").disabled=currentPage<=0;$("#nextPage").disabled=currentPage>=nodes.length-1}
async function buildThumbs(){const strip=$("#thumbStrip");strip.innerHTML="";const end=Math.min(8,nodes.length);for(let i=0;i<end;i++){const b=document.createElement("button");b.className="viewer-thumb";b.type="button";const c=document.createElement("canvas");c.width=90;c.height=110;b.appendChild(c);const s=document.createElement("span");s.textContent=i+1;b.appendChild(s);b.onclick=()=>showMainPage(i);strip.appendChild(b);try{preparePage(i);await waitForContent(nodes[i]);const canvas=await html2canvas(nodes[i],{scale:.35,backgroundColor:"#fff",useCORS:true,allowTaint:false,logging:false,imageTimeout:12000});const ctx=c.getContext("2d");ctx.drawImage(canvas,0,0,c.width,c.height)}catch(e){const x=c.getContext("2d");x.fillStyle="#fff";x.fillRect(0,0,c.width,c.height);x.fillStyle="#777";x.textAlign="center";x.font="bold 12px sans-serif";x.fillText(`PAGE ${i+1}`,45,55)}}setProgress(4+(i+1)/end*7,`Building preview ${i+1} of ${end}…`)}preparePage(currentPage);updateViewerScale();updateThumbs()}
function updateThumbs(){document.querySelectorAll(".viewer-thumb").forEach((b,i)=>b.classList.toggle("active",i===currentPage));const status=$("#thumbStatus");if(status)status.textContent=`Showing page ${currentPage+1} of ${nodes.length} · Use ← → or the arrows to navigate`}
$("#prevPage").onclick=()=>showMainPage(currentPage-1);$("#nextPage").onclick=()=>showMainPage(currentPage+1);$("#thumbPrev").onclick=()=>showMainPage(Math.max(0,currentPage-8));$("#thumbNext").onclick=()=>showMainPage(Math.min(nodes.length-1,currentPage+8));$("#zoomIn").onclick=()=>{zoom=Math.min(2.5,zoom+.1);updateViewerScale()};$("#zoomOut").onclick=()=>{zoom=Math.max(.5,zoom-.1);updateViewerScale()};$("#fitBtn").onclick=()=>{zoom=1;updateViewerScale()};$("#fullBtn").onclick=async()=>{const el=$("#previewViewer");if(!document.fullscreenElement)await el.requestFullscreen?.();else await document.exitFullscreen?.()};document.addEventListener("keydown",e=>{if(e.key==="ArrowLeft")showMainPage(currentPage-1);if(e.key==="ArrowRight")showMainPage(currentPage+1)});
/* Large-PDF streaming writer. v6 intentionally has no `this.handle.write` path. */
const enc=new TextEncoder(),bytes=s=>enc.encode(s);
class StreamPDF{constructor(w,total){this.w=w;this.offset=0;this.offsets=[];this.total=total}async write(b){if(typeof this.w.write!=="function")throw new Error("PDF writer is not available. Please refresh the GitHub Pages site so the latest app.js loads.");await this.w.write(b);this.offset+=b.length}async obj(id,parts){this.offsets[id]=this.offset;await this.write(bytes(`${id} 0 obj\n`));for(const p of parts)await this.write(typeof p==="string"?bytes(p):p);await this.write(bytes("\nendobj\n"))}po(i){return 3+i*3}co(i){return 4+i*3}io(i){return 5+i*3}async start(){await this.write(new Uint8Array([37,80,68,70,45,49,46,52,10,37,226,227,207,211,10]));const kids=Array.from({length:this.total},(_,i)=>`${this.po(i)} 0 R`).join(" ");await this.obj(1,["<< /Type /Catalog /Pages 2 0 R >>"]);await this.obj(2,[`<< /Type /Pages /Count ${this.total} /Kids [ ${kids} ] >>`])}async add(i,w,h,j,jw,jh){const po=this.po(i),co=this.co(i),io=this.io(i),ct=`q\n${w} 0 0 ${h} 0 0 cm\n/Im1 Do\nQ\n`;await this.obj(po,[`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${w} ${h}] /Resources << /XObject << /Im1 ${io} 0 R >> >> /Contents ${co} 0 R >>`]);await this.obj(co,[`<< /Length ${bytes(ct).length} >>\nstream\n`,ct,"endstream"]);await this.obj(io,[`<< /Type /XObject /Subtype /Image /Width ${jw} /Height ${jh} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${j.length} >>\nstream\n`,j,"\nendstream"])}async finish(){const x=this.offset,n=3+this.total*3;await this.write(bytes(`xref\n0 ${n}\n0000000000 65535 f \n`));for(let i=1;i<n;i++)await this.write(bytes(String(this.offsets[i]).padStart(10,"0")+" 00000 n \n"));await this.write(bytes(`trailer\n<< /Size ${n} /Root 1 0 R >>\nstartxref\n${x}\n%%EOF\n`));await this.w.close()}}
async function jpeg(c){const b=await new Promise(r=>c.toBlob(r,"image/jpeg",.97));if(!b)throw new Error("Could not encode page image.");return new Uint8Array(await b.arrayBuffer())}
async function getWriter(name){if(!window.showSaveFilePicker)throw new Error("This GitHub Pages build needs Chrome or Edge with the File System Access API.");const h=await window.showSaveFilePicker({suggestedName:name,types:[{description:"PDF document",accept:{"application/pdf":[".pdf"]}}]});const w=await h.createWritable();if(!w||typeof w.write!=="function")throw new Error("The browser returned an invalid PDF writer.");return w}
async function exportPDF(){if(!selectedFile||!pageDefinitions.length)return;startBtn.disabled=true;let w=null;const f=makeFrame();try{const base=selectedFile.name.replace(/\.(html?|HTML?)$/,""),quality=+$("#quality").value,delay=+$("#delay").value;w=await getWriter(`${base}.pdf`);const pdf=new StreamPDF(w,pageDefinitions.length);await pdf.start();setProgress(10,"Loading document for export…");f.srcdoc=sourceText;await new Promise(resolve=>{let done=false,finish=()=>{if(!done){done=true;resolve()}};f.addEventListener("load",finish,{once:true});setTimeout(finish,15000)});const d=f.contentDocument;if(!d)throw new Error("Could not access the document viewer.");cleanDoc(d);await sleep(3500);const ns=Array.from(d.querySelectorAll('[id^="outer_page_"]'));if(!ns.length)throw new Error("No document pages were rendered.");for(let i=0;i<ns.length;i++){const n=ns[i];n.scrollIntoView({block:"center"});await sleep(delay);const r=n.getBoundingClientRect();if(r.width<2||r.height<2)throw new Error(`Page ${i+1} has no visible document area.`);const c=await html2canvas(n,{scale:quality,backgroundColor:"#fff",useCORS:true,allowTaint:false,logging:false,imageTimeout:20000});const j=await jpeg(c),def=pageDefinitions[i]||{width:r.width,height:r.height};await pdf.add(i,def.width,def.height,j,c.width,c.height);c.width=1;c.height=1;setProgress(10+(i+1)/ns.length*87,`Writing page ${i+1} of ${ns.length}…`);if(i%2===0)await sleep(10)}await pdf.finish();w=null;setProgress(100,`Done — ${ns.length} pages saved.`);alert("PDF created successfully.")}catch(e){console.error(e);setProgress(0,e.name==="AbortError"?"Export cancelled.":"Export failed.");if(w)try{await w.abort()}catch(_){}if(e.name!=="AbortError")alert("Export failed.\n\n"+e.message+"\n\nIf you still see `this.handle.write is not a function`, refresh the GitHub Pages site with Ctrl+F5. The old JavaScript is cached in the browser.")}finally{f.remove();startBtn.disabled=false}}
startBtn.onclick=exportPDF;fileInput.onchange=e=>loadFile(e.target.files[0]);["dragenter","dragover"].forEach(t=>dropZone.addEventListener(t,e=>{e.preventDefault();dropZone.classList.add("drag")}));["dragleave","drop"].forEach(t=>dropZone.addEventListener(t,e=>{e.preventDefault();dropZone.classList.remove("drag")}));dropZone.ondrop=e=>loadFile(e.dataTransfer.files[0]);dropZone.onkeydown=e=>{if(e.key==="Enter"||e.key===" ")fileInput.click()};$("#removeFile").onclick=()=>location.reload();$("#themeBtn").onclick=()=>{document.documentElement.classList.toggle("light");$("#themeBtn").textContent=document.documentElement.classList.contains("light")?"☀":"☾"};
